language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - os: osx
      language: generic
      python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install matplotlib==2.0.2
  - python setup.py install

script:
  - python ./phidl/phidl_tutorial_example.py